apiVersion: v1
kind: Service
metadata:
  name: fitlife-service
spec:
  selector:
    app: fitlife
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort if using Minikube
